# Generated by Django 2.2 on 2019-04-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20190409_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
